"""init reports

Revision ID: 5e85c8d7a6bb
Revises: 
Create Date: 2026-05-13 16:59:13.242750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5e85c8d7a6bb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Enum('analyzing', 'awaiting_confirmation', 'generating', 'completed', 'failed', name='report_status'), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('brand_name', sa.String(length=255), nullable=True),
    sa.Column('brand_domain', sa.String(length=255), nullable=True),
    sa.Column('brand_aliases', sa.JSON(), nullable=True),
    sa.Column('brand_description', sa.Text(), nullable=True),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('competitors', sa.JSON(), nullable=True),
    sa.Column('prompts', sa.JSON(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('aeo_score', sa.Float(), nullable=True),
    sa.Column('citation_rate', sa.Float(), nullable=True),
    sa.Column('mention_rate', sa.Float(), nullable=True),
    sa.Column('sentiment_summary', sa.Enum('positive', 'neutral', 'mixed', 'negative', name='sentiment_summary'), nullable=True),
    sa.Column('source_share_of_voice', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports')
    # ### end Alembic commands ###
